#!/bin/sh
#
# stage2 (c) 1997-2008 Petter N Hagen
# part of ntchangepasswd bootdisk scripts
#
# General setup continued
# After init has detached from the console devices
#

echo "In stage 2"

#exec </dev/console >/dev/console 2>/dev/console

#/bin/udevstart



# Wait up to 10 s for NVMe/SATA async probe to settle
for i in 1 2 3 4 5 6 7 8 9 10; do
    grep -qE '(sd[a-z]|nvme[0-9]|vd[a-z]|hd[a-z])' /proc/partitions && break
    sleep 1
done
# Reset VT consoles to clean 80x25 state
for vt in 1 2 3 4; do printf '\033[2J' > /dev/tty${vt} 2>/dev/null || true; done
mdev -s

echo "Spawning shells on console 2 - 4"

for i in 1 2 3 4 
do
    case $i in
       1) ;;
       *) openvt
    esac
done

mkdir /tmp /disk
chmod 777 /tmp

echo "Initialization complete!"

sh /scripts/prepdriver.sh

mdev -s

cat /scripts/banner1

sh /scripts/main.sh

sh

echo "if you really want to exit, type reboot or press ctrl-alt-del"

